# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyproject', models.CharField(max_length=50, verbose_name='\u7533\u8bf7\u7f16\u53f7')),
                ('status', models.CharField(choices=[('WC', '\u5f85\u63d0\u4ea4'), ('WD', '\u5f85\u53d1\u5e03'), ('C', '\u5df2\u53d6\u6d88'), ('D', '\u5df2\u53d1\u5e03'), ('DA', '\u7814\u53d1\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('OA', '\u8fd0\u7ef4\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('EA', '\u8fd0\u7ef4\u5de5\u7a0b\u5e08\u5ba1\u6279\u4e2d'), ('TA', '\u6d4b\u8bd5\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('TDA', '\u6280\u672f\u603b\u76d1\u5ba1\u6279\u4e2d')], default='WC', max_length=3, verbose_name='\u72b6\u6001')),
                ('apply_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7533\u8bf7\u4eba')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('deploy_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u53d1\u5e03\u4eba')),
                ('deploy_time', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('confamendexplain', models.TextField(blank=True, null=True, verbose_name='\u914d\u7f6e\u4fee\u6539\u8bf4\u660e')),
                ('remarkexplain', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8\u4e8b\u9879')),
                ('apply_status', models.CharField(blank=True, choices=[('Y', '\u5ba1\u6279\u901a\u8fc7'), ('N', '\u5ba1\u6279\u4e0d\u901a\u8fc7')], max_length=1, null=True, verbose_name='\u5ba1\u6838\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='Configfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitecluster', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deployitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployorderby', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u53d1\u5e03\u987a\u5e8f')),
                ('jenkinsversion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jenkins\u7248\u672c\u53f7')),
                ('type', models.CharField(choices=[('T', '\u4e3b\u5e72'), ('B', '\u5206\u652f')], default='T', max_length=1, verbose_name='\u4ee3\u7801\u7c7b\u578b')),
                ('deploy_status', models.CharField(choices=[('Y', '\u5df2\u53d1\u5e03'), ('N', '\u5f85\u53d1\u5e03')], default='N', max_length=1, verbose_name='\u53d1\u5e03\u72b6\u6001')),
                ('applyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Apply')),
            ],
        ),
        migrations.CreateModel(
            name='ECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instanceid', models.CharField(max_length=30)),
                ('IP', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('\u542f\u7528', 'enable'), ('\u7981\u7528', 'disable')], default='\u542f\u7528', max_length=10)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('color_code', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConfigfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sitecluster', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical configfile',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=30)),
                ('configdirname', models.CharField(max_length=50)),
                ('port', models.PositiveSmallIntegerField(null=True)),
                ('testpage', models.CharField(max_length=30, null=True)),
                ('devcharge', models.CharField(max_length=10, null=True)),
                ('deployattention', models.TextField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('modified_user', models.CharField(default='admin', max_length=20)),
                ('status', models.CharField(choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1)),
                ('ECSlists', models.ManyToManyField(to='configmanager.ECS')),
                ('configfiles', models.ManyToManyField(blank=True, to='configmanager.Configfile')),
            ],
        ),
        migrations.AddField(
            model_name='deployitem',
            name='deploysite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site', verbose_name='\u53d1\u5e03\u7ad9\u70b9'),
        ),
    ]
