# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigmanagerHistoricalconfigfile',
            fields=[
                ('id', models.IntegerField()),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1)),
                ('site_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configmanager_historicalconfigfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyproject', models.CharField(max_length=50, verbose_name='\u7533\u8bf7\u7f16\u53f7')),
                ('status', models.CharField(choices=[('WC', '\u5f85\u63d0\u4ea4'), ('WD', '\u5f85\u53d1\u5e03'), ('C', '\u5df2\u53d6\u6d88'), ('D', '\u5df2\u53d1\u5e03'), ('DA', '\u7814\u53d1\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('OA', '\u8fd0\u7ef4\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('EA', '\u8fd0\u7ef4\u5de5\u7a0b\u5e08\u5ba1\u6279\u4e2d'), ('TA', '\u6d4b\u8bd5\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('TDA', '\u6280\u672f\u603b\u76d1\u5ba1\u6279\u4e2d')], default='WC', max_length=3, verbose_name='\u72b6\u6001')),
                ('apply_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7533\u8bf7\u4eba')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('deploy_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u53d1\u5e03\u4eba')),
                ('deploy_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b9e\u9645\u53d1\u5e03\u65f6\u95f4')),
                ('confamendexplain', models.TextField(blank=True, null=True, verbose_name='\u914d\u7f6e\u4fee\u6539\u8bf4\u660e')),
                ('remarkexplain', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8\u4e8b\u9879')),
                ('apply_status', models.CharField(blank=True, choices=[('Y', '\u5ba1\u6279\u901a\u8fc7'), ('N', '\u5ba1\u6279\u4e0d\u901a\u8fc7')], max_length=1, null=True, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('wishdeploy_time', models.DateField(blank=True, null=True, verbose_name='\u671f\u671b\u53d1\u5e03\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('OperatorName', models.CharField(max_length=30)),
                ('OperationTime', models.DateTimeField()),
                ('applyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Apply')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeployECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ECSdeploystatus', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deployitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployorderby', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u53d1\u5e03\u987a\u5e8f')),
                ('jenkinsversion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jenkins\u7248\u672c\u53f7')),
                ('type', models.CharField(choices=[('T', '\u4e3b\u5e72'), ('B', '\u5206\u652f')], default='T', max_length=1, verbose_name='\u4ee3\u7801\u7c7b\u578b')),
                ('applyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Apply')),
            ],
        ),
        migrations.CreateModel(
            name='ECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ECS\u540d\u79f0')),
                ('instanceid', models.CharField(max_length=30, verbose_name='\u5b9e\u4f8bID')),
                ('IP', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP\u5730\u5740')),
                ('status', models.CharField(choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1)),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('recently_cpu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6700\u8fd1CPU\u4f7f\u7528\u7387')),
                ('recently_memory', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6700\u8fd1\u5185\u5b58\u4f7f\u7528\u7387')),
                ('recently_diskusage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6700\u8fd1\u78c1\u76d8\u4f7f\u7528\u7387')),
                ('regionId', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6240\u5728\u533a\u57df')),
                ('expiredtime', models.DateTimeField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('memory', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('ostype', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('instancestatus', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5b9e\u4f8b\u72b6\u6001')),
                ('networktype', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7f51\u7edc\u7c7b\u578b')),
                ('cpu', models.CharField(blank=True, max_length=5, null=True, verbose_name='CPU\u6838\u6570')),
                ('publicipaddress', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='\u516c\u7f51IP')),
                ('osname', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'ECS\u4fe1\u606f\u8868',
                'verbose_name_plural': 'ECS\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConfigfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical configfile',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Y', '\u5df2\u53d1\u5e03'), ('N', '\u5f85\u53d1\u5e03')], default='N', max_length=1, verbose_name='\u914d\u7f6e\u72b6\u6001')),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('ECS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=30)),
                ('configdirname', models.CharField(max_length=50)),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('testpage', models.CharField(max_length=30, null=True)),
                ('devcharge', models.CharField(blank=True, max_length=10, null=True)),
                ('deployattention', models.TextField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('modified_user', models.CharField(default='admin', max_length=20)),
                ('status', models.CharField(choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1)),
                ('ECSlists', models.ManyToManyField(to='configmanager.ECS')),
            ],
        ),
        migrations.CreateModel(
            name='Siterace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceid', models.BigIntegerField()),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('networktype', models.CharField(blank=True, max_length=10, null=True)),
                ('addresstype', models.CharField(max_length=10)),
                ('createdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SLBhealthstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLBstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('healthstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('ECS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS')),
                ('SLB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.SLB')),
            ],
        ),
        migrations.CreateModel(
            name='SLBsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.SLB')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='siterace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.Siterace'),
        ),
        migrations.AddField(
            model_name='release',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Person'),
        ),
        migrations.AddField(
            model_name='historicalconfigfile',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configmanager.Site'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='configmanager.Membership', to='configmanager.Person'),
        ),
        migrations.AddField(
            model_name='deployitem',
            name='deploysite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site', verbose_name='\u53d1\u5e03\u7ad9\u70b9'),
        ),
        migrations.AddField(
            model_name='deployecs',
            name='ECS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS'),
        ),
        migrations.AddField(
            model_name='deployecs',
            name='applyproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Apply'),
        ),
        migrations.AddField(
            model_name='deployecs',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site'),
        ),
        migrations.AddField(
            model_name='configfile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site'),
        ),
    ]
