# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instanceid', models.CharField(max_length=30)),
                ('IP', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('modified_user', models.PositiveSmallIntegerField()),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=30)),
                ('configdirname', models.CharField(max_length=50)),
                ('configfilesname', models.CharField(max_length=100)),
                ('ECSlists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
