# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='status',
            field=models.CharField(choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1),
        ),
    ]
