# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='status',
            field=models.CharField(choices=[('y', 'enable'), ('n', 'disable')], default='y', max_length=1),
        ),
    ]
