# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0002_auto_20180530_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
