# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0002_alarm_history_rds_rds_usage_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u544a\u8b66\u89c4\u5219\u540d\u79f0')),
                ('namespace', models.CharField(max_length=30, verbose_name='\u544a\u8b66\u4ea7\u54c1\u540d\u79f0')),
                ('alarm_time', models.DateTimeField(blank=True, null=True, verbose_name='\u544a\u8b66\u65f6\u95f4')),
                ('value', models.CharField(max_length=10, verbose_name='\u544a\u8b66\u7684\u5f53\u524d\u503c')),
                ('instance_name', models.CharField(max_length=50, verbose_name='\u544a\u8b66\u5b9e\u4f8b\u540d\u79f0')),
                ('metric_name', models.CharField(max_length=50, verbose_name='\u76d1\u63a7\u9879\u540d\u79f0')),
                ('dimension', models.CharField(max_length=200, verbose_name='\u544a\u8b66\u8be6\u60c5')),
            ],
            options={
                'verbose_name': '\u544a\u8b66\u5386\u53f2',
                'verbose_name_plural': '\u544a\u8b66\u5386\u53f2',
            },
        ),
        migrations.CreateModel(
            name='RDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100, verbose_name='\u5b9e\u4f8bID')),
                ('instance_alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b9e\u4f8b\u522b\u540d')),
                ('network_type', models.CharField(max_length=20, verbose_name='\u7f51\u7edc\u7c7b\u578b')),
                ('engine', models.CharField(max_length=30, verbose_name='\u5f15\u64ce\u7c7b\u578b')),
                ('engine_version', models.CharField(max_length=50, verbose_name='\u5f15\u64ce\u7248\u672c')),
                ('status', models.CharField(max_length=30, verbose_name='\u72b6\u6001')),
                ('expire_time', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'RDS\u4fe1\u606f\u8868',
                'verbose_name_plural': 'RDS\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='RDS_Usage_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU\u4f7f\u7528\u7387')),
                ('io_usage', models.FloatField(blank=True, null=True, verbose_name='IOPS\u4f7f\u7528\u7387')),
                ('disk_usage', models.FloatField(blank=True, null=True, verbose_name='\u78c1\u76d8\u4f7f\u7528\u7387')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('rds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.RDS', verbose_name='\u6240\u5c5eRDS')),
            ],
            options={
                'verbose_name': 'RDS\u8d44\u6e90\u4f7f\u7528\u7387\u8bb0\u5f55\u8868',
                'verbose_name_plural': 'RDS\u8d44\u6e90\u4f7f\u7528\u7387\u8bb0\u5f55\u8868',
            },
        ),
    ]
