# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0003_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployitem',
            name='deployecs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS', verbose_name='\u5173\u8054ECS'),
        ),
    ]
