# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0004_deployitem_deployecs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployitem',
            name='deployecs',
        ),
        migrations.AddField(
            model_name='deployitem',
            name='deployecs',
            field=models.ManyToManyField(blank=True, null=True, to='configmanager.ECS', verbose_name='\u5173\u8054ECS'),
        ),
    ]
