# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0005_auto_20180517_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecs',
            name='modified_userid',
        ),
    ]
