# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0005_auto_20180531_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployitem',
            name='deployecs',
        ),
    ]
