# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0006_remove_ecs_modified_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='modified_user',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
