# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0006_remove_deployitem_deployecs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecs',
            name='color_code',
        ),
        migrations.AlterField(
            model_name='ecs',
            name='status',
            field=models.CharField(choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1),
        ),
    ]
