# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0009_auto_20180517_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='modified_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.User'),
        ),
    ]
