# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0009_auto_20180611_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='siterace',
        ),
        migrations.DeleteModel(
            name='SiteRace',
        ),
    ]
