# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0010_auto_20180612_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siterace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceid', models.PositiveSmallIntegerField()),
                ('siteid', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
