# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0014_configfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='deployattention',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='devcharge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='site',
            name='modified_user',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='port',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='testpage',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
