# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0015_auto_20180518_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='site',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='conf_text',
            field=models.CharField(max_length=30),
        ),
    ]
