# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0016_auto_20180615_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='devcharge',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
