# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0016_auto_20180518_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site'),
        ),
    ]
