# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0017_auto_20180518_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='ECSlists',
        ),
        migrations.AddField(
            model_name='site',
            name='ECSlists',
            field=models.ManyToManyField(to='configmanager.ECS'),
        ),
    ]
