# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0018_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('Y', '\u5df2\u53d1\u5e03'), ('N', '\u5f85\u53d1\u5e03')], default='N', max_length=1, verbose_name='\u914d\u7f6e\u72b6\u6001'),
        ),
    ]
