# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0019_release_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigmanagerHistoricalconfigfile',
            fields=[
                ('id', models.IntegerField()),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1)),
                ('site_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configmanager_historicalconfigfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
