# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0019_auto_20180518_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='configfilesname',
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1),
        ),
    ]
