# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0020_auto_20180518_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
