# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0020_authuser_configmanagerhistoricalconfigfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_time',
            field=models.DateTimeField(verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
    ]
