# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0021_configfile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
