# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0021_auto_20180703_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
    ]
