# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0022_auto_20180519_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configfile',
            name='site',
        ),
        migrations.AddField(
            model_name='site',
            name='configfiles',
            field=models.ManyToManyField(to='configmanager.Configfile'),
        ),
    ]
