# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0023_auto_20180519_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='SiteCluster',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
