# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0025_configfile_modified_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configfile',
            old_name='conf_text',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='configfile',
            old_name='SiteCluster',
            new_name='sitecluster',
        ),
    ]
