# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0025_apply_wishapply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='deploy_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5b9e\u9645\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
