# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0028_auto_20180519_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='sitecluster',
            field=models.CharField(max_length=30),
        ),
    ]
