# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0029_auto_20180519_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='configfiles',
            field=models.ManyToManyField(blank=True, to='configmanager.Configfile'),
        ),
    ]
