# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0030_auto_20180519_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='modified_user',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
