# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0030_ecs_recently_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='recently_memory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
