# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0031_configfile_modified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='modified_user',
            field=models.CharField(max_length=20),
        ),
    ]
