# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0032_ecs_recently_disk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs',
            old_name='recently_disk',
            new_name='recently_diskusage',
        ),
    ]
