# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configmanager', '0032_auto_20180519_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfigfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sitecluster', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical configfile',
            },
        ),
    ]
