# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0033_historicalconfigfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyproject', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('WC', '\u5f85\u63d0\u4ea4'), ('WD', '\u5f85\u53d1\u5e03'), ('C', '\u5df2\u53d6\u6d88'), ('D', '\u5df2\u53d1\u5e03'), ('DA', '\u7814\u53d1\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('OA', '\u8fd0\u7ef4\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('EA', '\u8fd0\u7ef4\u5de5\u7a0b\u5e08\u5ba1\u6279\u4e2d'), ('TA', '\u6d4b\u8bd5\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('TDA', '\u6280\u672f\u603b\u76d1\u5ba1\u6279\u4e2d')], default='WC', max_length=3)),
                ('apply_user', models.CharField(max_length=20)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('deploy_user', models.CharField(blank=True, max_length=20, null=True)),
                ('deploy_time', models.DateTimeField(blank=True, null=True)),
                ('confamendexplain', models.TextField(blank=True, null=True)),
                ('remarkexplain', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deployitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployorderby', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jenkinsversion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('T', '\u4e3b\u5e72'), ('B', '\u5206\u652f')], default='T', max_length=1)),
                ('status', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1)),
                ('applyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Apply')),
                ('deploysite', models.ManyToManyField(blank=True, to='configmanager.Site')),
            ],
        ),
    ]
