# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0035_remove_ecs_inneripaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs',
            old_name='instanceName',
            new_name='instancename',
        ),
        migrations.RenameField(
            model_name='ecs',
            old_name='networkType',
            new_name='networktype',
        ),
        migrations.RenameField(
            model_name='ecs',
            old_name='publicIpAddress',
            new_name='publicipaddress',
        ),
    ]
