# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0035_auto_20180523_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployitem',
            name='apply_status',
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_status',
            field=models.CharField(choices=[('Y', '\u5ba1\u6279\u901a\u8fc7'), ('N', '\u5ba1\u6279\u4e0d\u901a\u8fc7')], default='Y', max_length=1),
        ),
    ]
