# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0037_remove_ecs_instancename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs',
            old_name='expiredTime',
            new_name='expiredtime',
        ),
    ]
