# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0037_auto_20180523_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_user',
            field=models.CharField(default='admin', editable=False, max_length=20),
        ),
    ]
