# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0038_auto_20180523_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
