# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0039_auto_20180523_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployitem',
            name='deploysite',
        ),
        migrations.AddField(
            model_name='deployitem',
            name='deploysite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site'),
        ),
    ]
