# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0040_auto_20180524_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='confamendexplain',
        ),
        migrations.AddField(
            model_name='apply',
            name='Confamendexplain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
