# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0040_auto_20180712_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=30)),
                ('networktype', models.CharField(max_length=10)),
                ('createdate', models.DateField()),
            ],
        ),
    ]
