# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0041_auto_20180524_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Confamendexplain',
            new_name='confamendexplain',
        ),
    ]
