# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0042_auto_20180713_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLBhealthstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLBstatus', models.CharField(max_length=5)),
                ('healthstatus', models.CharField(max_length=5)),
                ('ECS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS')),
                ('SLB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.SLB')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site')),
            ],
        ),
    ]
