# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0042_auto_20180524_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='confamendexplain',
            field=models.TextField(blank=True, null=True, verbose_name="person's first name"),
        ),
    ]
