# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0043_slbhealthstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLBsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.SLB')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site')),
            ],
        ),
        migrations.RemoveField(
            model_name='slbhealthstatus',
            name='SLB',
        ),
        migrations.RemoveField(
            model_name='slbhealthstatus',
            name='site',
        ),
        migrations.AlterField(
            model_name='slbhealthstatus',
            name='ECS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS'),
        ),
        migrations.AddField(
            model_name='slbhealthstatus',
            name='SLBsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.SLBsite'),
        ),
    ]
