# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0043_auto_20180524_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='confamendexplain',
            field=models.TextField(blank=True, null=True, verbose_name='\u914d\u7f6e\u4fee\u6539\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='remarkexplain',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8\u4e8b\u9879'),
        ),
    ]
