# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0044_auto_20180716_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slbhealthstatus',
            name='ECS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS'),
        ),
        migrations.AlterField(
            model_name='slbhealthstatus',
            name='SLBsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.SLBsite'),
        ),
    ]
