# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0044_auto_20180524_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_status',
            field=models.CharField(choices=[('Y', '\u5ba1\u6279\u901a\u8fc7'), ('N', '\u5ba1\u6279\u4e0d\u901a\u8fc7')], default='Y', max_length=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='apply_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7533\u8bf7\u4eba'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='applyproject',
            field=models.CharField(max_length=50, verbose_name='\u7533\u8bf7\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='deploy_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='deploy_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u53d1\u5e03\u4eba'),
        ),
    ]
