# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0045_auto_20180524_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_status',
            field=models.CharField(choices=[('Y', '\u5ba1\u6279\u901a\u8fc7'), ('N', '\u5ba1\u6279\u4e0d\u901a\u8fc7')], default='Y', max_length=1, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('WC', '\u5f85\u63d0\u4ea4'), ('WD', '\u5f85\u53d1\u5e03'), ('C', '\u5df2\u53d6\u6d88'), ('D', '\u5df2\u53d1\u5e03'), ('DA', '\u7814\u53d1\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('OA', '\u8fd0\u7ef4\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('EA', '\u8fd0\u7ef4\u5de5\u7a0b\u5e08\u5ba1\u6279\u4e2d'), ('TA', '\u6d4b\u8bd5\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('TDA', '\u6280\u672f\u603b\u76d1\u5ba1\u6279\u4e2d')], default='WC', max_length=3, verbose_name='\u72b6\u6001'),
        ),
    ]
