# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0046_auto_20180716_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slbhealthstatus',
            name='SLB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.SLB'),
        ),
    ]
