# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0046_auto_20180524_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployitem',
            name='deploy_status',
            field=models.CharField(choices=[('Y', '\u5df2\u53d1\u5e03'), ('N', '\u5f85\u53d1\u5e03')], default='N', max_length=1, verbose_name='\u53d1\u5e03\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='deployitem',
            name='deployorderby',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u53d1\u5e03\u987a\u5e8f'),
        ),
        migrations.AlterField(
            model_name='deployitem',
            name='jenkinsversion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jenkins\u7248\u672c\u53f7'),
        ),
        migrations.AlterField(
            model_name='deployitem',
            name='type',
            field=models.CharField(choices=[('T', '\u4e3b\u5e72'), ('B', '\u5206\u652f')], default='T', max_length=1, verbose_name='\u4ee3\u7801\u7c7b\u578b'),
        ),
    ]
