# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0047_auto_20180716_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='slb',
            name='addresstype',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slb',
            name='networktype',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
