# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0047_auto_20180524_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployitem',
            name='deploysite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site', verbose_name='\u53d1\u5e03\u7ad9\u70b9'),
        ),
    ]
