# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0049_auto_20180716_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slbhealthstatus',
            name='SLBstatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slbhealthstatus',
            name='healthstatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
