# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0049_auto_20180525_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_status',
            field=models.CharField(blank=True, choices=[('Y', '\u5ba1\u6279\u901a\u8fc7'), ('N', '\u5ba1\u6279\u4e0d\u901a\u8fc7')], max_length=1, null=True, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
    ]
