# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0050_auto_20180716_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ECSdeploystatus', models.CharField(max_length=1)),
                ('ECS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.ECS')),
                ('applyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Apply')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Site')),
            ],
        ),
    ]
