# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0051_deployecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployecs',
            name='ECSdeploystatus',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
