# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configmanager', '0052_auto_20180525_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApply',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('applyproject', models.CharField(max_length=50, verbose_name='\u7533\u8bf7\u7f16\u53f7')),
                ('status', models.CharField(choices=[('WC', '\u5f85\u63d0\u4ea4'), ('WD', '\u5f85\u53d1\u5e03'), ('C', '\u5df2\u53d6\u6d88'), ('D', '\u5df2\u53d1\u5e03'), ('DA', '\u7814\u53d1\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('OA', '\u8fd0\u7ef4\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('EA', '\u8fd0\u7ef4\u5de5\u7a0b\u5e08\u5ba1\u6279\u4e2d'), ('TA', '\u6d4b\u8bd5\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('TDA', '\u6280\u672f\u603b\u76d1\u5ba1\u6279\u4e2d')], default='WC', max_length=3, verbose_name='\u72b6\u6001')),
                ('apply_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7533\u8bf7\u4eba')),
                ('apply_time', models.DateTimeField(blank=True, editable=False, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('deploy_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u53d1\u5e03\u4eba')),
                ('deploy_time', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('confamendexplain', models.TextField(blank=True, null=True, verbose_name='\u914d\u7f6e\u4fee\u6539\u8bf4\u660e')),
                ('remarkexplain', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8\u4e8b\u9879')),
                ('apply_status', models.CharField(blank=True, choices=[('Y', '\u5ba1\u6279\u901a\u8fc7'), ('N', '\u5ba1\u6279\u4e0d\u901a\u8fc7')], max_length=1, null=True, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical apply',
            },
        ),
    ]
