# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0053_auto_20180721_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='IP',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='publicipaddress',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
