# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0053_historicalapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalapply',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalApply',
        ),
    ]
