# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0054_auto_20180721_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('OperatorName', models.CharField(max_length=20)),
                ('OperationTime', models.DateTimeField(blank=True, null=True)),
                ('applyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configmanager.Apply')),
            ],
        ),
    ]
