# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0055_applyoperatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyoperatelog',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
