# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmanager', '0058_auto_20180730_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='publicipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
